version: '2.1'
orbs:
  gradle: circleci/gradle@3.0.0
workflows:
  test-with-custom-reports:
    jobs:
      - gradle/test:
          test_command: musixtream-test
          test_results_path: build/test-results/