version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0
    resource_class: daan/musixtream
    steps:
      - checkout
  test:
    docker:
      - image: cimg/openjdk:21.0
    resource_class: daan/musixtream
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: ./gradlew check
      - store_test_results:
          path: build/test-results
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
      - store_artifacts:
          path: build/reports
workflows:
  build:
    jobs:
      - build:
          requires:
            - test