#file: noinspection YAMLSchemaValidation
version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:21.0.2
    resource_class: daan/musixtream
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          name: Restore cache
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Grade build
          command: ./gradlew clean build
      - save_cache:
          name: Store cache
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
  deploy:
    docker:
      - image: cimg/openjdk:21.0.2
    resource_class: daan/musixtream
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          name: Restore cache
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Install kubectl
          command: |
            curl -LO https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Kubectl get pods
          command: kubectl get pods
      - run:
          name: Deploy to Minikube
          command: |
            kubectl apply -f ./kubernetes
      - save_cache:
          name: Store cache
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
workflows:
  build-test-deploy:
    jobs:
      - build_and_test
      - deploy