apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- musixtream-deployment.yaml
- musixtream-svc.yaml
- namespace.yaml
namespace: nodejs
images:
- name: musixtream
  newName: musixtream
  newTag: v1
- name: musixtream-backend
  newName: /musixtream-backend
  newTag: latest
