apiVersion: v1
kind: Namespace
metadata:
  name: musixtream
  labels:
    name: musixtream
---
apiVersion: v1
kind: Service
metadata:
  name: musixtream-backend
  namespace: musixtream
spec:
  selector:
    app: musixtream
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: musixtream-backend
  namespace: musixtream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musixtream
      tier: backend
  template:
    metadata:
      labels:
        app: musixtream
        tier: backend
    spec:
      containers:
        - name: musixtream-backend
          image: dudesjef/musixtream-backend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
      restartPolicy: Always
      automountServiceAccountToken: false