apiVersion: apps/v1
kind: Deployment
metadata:
  name: musixtream-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: musixtream
  template:
    metadata:
      labels:
        app: musixtream
    spec:
      restartPolicy: Always
      containers:
        - name: musixtream-backend
          image: dudesjef/musixtream-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: musixtream-backend-service
  labels:
    app: musixtream
    service: musixtream-backend-service
spec:
  selector:
    app: musixtream
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: musixtream-backend-ingress
  namespace: musixtream
spec:
  rules:
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: musixtream-backend-service
              port:
                number: 80