apiVersion: apps/v1
kind: Deployment
metadata:
  name: musixtream-backend
spec:
  replicas: 3
  template:
    spec:
      restartPolicy: Always
      containers:
        - name: musixtream-backend
          image: dudesjef/musixtream-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: musixtream-backend-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080