apiVersion: v1
kind: Service
metadata:
  name: musixtream
  namespace: musixtream
spec:
  selector:
    app: musixtream
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  