name: Build and deploy to AKS
on:
  workflow_run:
    workflows: [ "Build and push Docker image" ]
    types: [ completed ]
    branches: main

env:
  AZURE_CONTAINER_REGISTRY: "musixtream"
  CONTAINER_NAME: "musixtream-backend"
  RESOURCE_GROUP: "Musixtream"
  CLUSTER_NAME: "Musixtream"
  DEPLOYMENT_MANIFEST_PATH: "../../kubernetes/musixtream-backend.yaml"

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2.1.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: IDENTITY
      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:latest --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} .